name: tp0
networks:
  testing_net:
    ipam:
      config:
      - subnet: 172.26.126.0/24
      driver: default
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    
    networks:
    - testing_net
    volumes:
    - ./server/config.ini:/config.ini
  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
    - CLI_ID=1
    - NOMBRE=Camila Rocio
    - APELLIDO=Varela
    - DOCUMENTO=37130775
    - NACIMIENTO=1995-05-09
    - NUMERO=4179
    networks:
    - testing_net
    depends_on:
    - server
    volumes:
    - ./client/config.yaml:/config.yaml
  client2:
    container_name: client2
    depends_on:
    - server
    entrypoint: /client
    environment:
    - CLI_ID=2
    - NOMBRE=Marcos Nahuel
    - APELLIDO=Rotman
    - DOCUMENTO=28625624
    - NACIMIENTO=2002-09-04
    - NUMERO=8117
    image: client:latest
    networks:
    - testing_net
    volumes:
    - ./client/config.yaml:/config.yaml
  client3:
    container_name: client3
    depends_on:
    - server
    entrypoint: /client
    environment:
    - CLI_ID=3
    - NOMBRE=Kiara Valentin
    - APELLIDO=Basile
    - DOCUMENTO=32250087
    - NACIMIENTO=1987-05-17
    - NUMERO=7364
    image: client:latest
    networks:
    - testing_net
    volumes:
    - ./client/config.yaml:/config.yaml
  client4:
    container_name: client4
    depends_on:
    - server
    entrypoint: /client
    environment:
    - CLI_ID=4
    - NOMBRE=Joaquin Sebastian
    - APELLIDO=Rivera
    - DOCUMENTO=21104770
    - NACIMIENTO=1980-12-11
    - NUMERO=7737
    image: client:latest
    networks:
    - testing_net
    volumes:
    - ./client/config.yaml:/config.yaml
  client5:
    container_name: client5
    depends_on:
    - server
    entrypoint: /client
    environment:
    - CLI_ID=5
    - NOMBRE=Milagros Jazmin
    - APELLIDO=Sosa
    - DOCUMENTO=37840762
    - NACIMIENTO=1991-12-20
    - NUMERO=6219
    image: client:latest
    networks:
    - testing_net
    volumes:
    - ./client/config.yaml:/config.yaml
  
version: '3.9'
